### ISSUE TITLE
CZ: Individuals type 2

### ISSUE THREAD

**Issue by sigriet** [ecovaci/JVatValidator#2]
Hi,

When I use this library to validate the Czech VAT number "CZ699000899", is returns false, yet when I use the site of VIES (http://ec.europa.eu/taxation_customs/vies/) it says that the VAT number is valid.
Maybe the validation rules changed of perhaps there is an error in the validation? According to the code this should be a Czech Individuals type 2 number.

Kind regards,
Sigriet Van Breusegem

**Comment by ecovaci** [comment]
Hello,

I have fixed this issue and released a new version (1.1.3).
Please test it again and let me know the result.

Thank you for support,
Eugen Covaci

**Comment by sigriet** [comment]
Hi,

It works now.
Thank you very much for the quick response.

Sigriet
